### ISSUE TITLE
libnginx-mod-http-passenger has broken dependency version on Bionic

### ISSUE THREAD

**Issue by infertux** [phusion/passenger_apt_automation#24] opened 2018-09-21 03:29 UTC
It's currently impossible to install Nginx and `libnginx-mod-http-passenger` at the same time as they depend on different versions of `nginx-common`:

```
$ sudo apt-get install nginx libnginx-mod-http-passenger                             
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: nginx-common (= 1.14.0-0ubuntu1) but 1.14.0-0ubuntu1.1 is to be installed
E: Unable to correct problems, you have held broken packages.

$ cat /etc/apt/sources.list.d/phusionpassenger.list 
deb      "https://oss-binaries.phusionpassenger.com/apt/passenger" bionic main
deb-src  "https://oss-binaries.phusionpassenger.com/apt/passenger" bionic main
```

**Comment by FooBarWidget** [comment] 2018-09-21 07:13
This is a duplicate of https://github.com/phusion/passenger/issues/2122.

**Closed by FooBarWidget** 2018-09-21 07:13 UTC
